FROM python:3.5

COPY . /application
WORKDIR /application

EXPOSE 8000
RUN apt-get install -y nginx
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

RUN pipenv run gunicorn --version

ENTRYPOINT scripts/entrypoint.sh